//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programming.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class calisanlar
    {
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string PersonelNo { get; set; }
        public string Yaptığı_iş { get; set; }
    }
}
